spring: #???? ??
  datasource: #???? 2?
    url: jdbc:h2:tcp://localhost/~/springProject #4?
    username: project
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
  # show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC
logging.level:
#  org.hibernate.SQL: debug
  org.hibernate.type: trace #???? 2?